name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --format=html --htmldir=flake8-report
      continue-on-error: true

    - name: Archive flake8 report
      if: failure() || success()
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: flake8-report

    - name: Run tests
      run: |
        pip install pytest pytest-html
        pytest --html=pytest-report.html --self-contained-html
      continue-on-error: true

    - name: Archive pytest report
      if: failure() || success()
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report
        path: pytest-report.html
