name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        run: |
          flake8 --format=html --htmldir=flake8-report

      - name: Run Pytest
        run: |
          pytest --html=pytest-report.html --self-contained-html

      - name: Upload Flake8 Report
        uses: actions/upload-artifact@v2
        with:
          name: flake8-report
          path: flake8-report

      - name: Upload Pytest Report
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: pytest-report.html
