name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8 flake8-html
        flake8 --format=html --htmldir=flake8-report
      continue-on-error: true

    - name: Check if flake8 report exists
      run: |
        if [ -d "flake8-report" ]; then echo "Flake8 report created successfully"; else echo "Flake8 report not created"; fi

    - name: Archive flake8 report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: flake8-report

    - name: Run tests
      run: |
        pip install pytest pytest-html
        pytest --html=pytest-report.html --self-contained-html
      continue-on-error: true

    - name: Check if pytest report exists
      run: |
        if [ -f "pytest-report.html" ]; then echo "Pytest report created successfully"; else echo "Pytest report not created"; fi

    - name: Archive pytest report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report
        path: pytest-report.html

    - name: Add test and lint reports to commit comment
      if: always()
      run: |
        echo "## Lint Report" > comment.md
        echo "[Flake8 Report](./flake8-report/index.html)" >> comment.md
        echo "## Test Report" >> comment.md
        echo "[Pytest Report](./pytest-report.html)" >> comment.md

    - name: Create a comment with reports
      if: always()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: comment.md
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
